// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk75NYbB7SCOzDmOmIL0tJB4DT5-MRGX8',
    appId: '1:463751360240:web:21d40cea8619fde8dadc35',
    messagingSenderId: '463751360240',
    projectId: 'evenlty-79b96',
    authDomain: 'evenlty-79b96.firebaseapp.com',
    storageBucket: 'evenlty-79b96.firebasestorage.app',
    measurementId: 'G-KJX3KQK559',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQyR300_Yra4fBKh3j_BB9I-0bdV7L5-g',
    appId: '1:463751360240:android:e35f69d4327a4685dadc35',
    messagingSenderId: '463751360240',
    projectId: 'evenlty-79b96',
    storageBucket: 'evenlty-79b96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeafiV4jS2ywnircMqMI_mCzZRuvELvys',
    appId: '1:463751360240:ios:59f47da73864f2f0dadc35',
    messagingSenderId: '463751360240',
    projectId: 'evenlty-79b96',
    storageBucket: 'evenlty-79b96.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeafiV4jS2ywnircMqMI_mCzZRuvELvys',
    appId: '1:463751360240:ios:59f47da73864f2f0dadc35',
    messagingSenderId: '463751360240',
    projectId: 'evenlty-79b96',
    storageBucket: 'evenlty-79b96.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk75NYbB7SCOzDmOmIL0tJB4DT5-MRGX8',
    appId: '1:463751360240:web:ecf161482dc422ffdadc35',
    messagingSenderId: '463751360240',
    projectId: 'evenlty-79b96',
    authDomain: 'evenlty-79b96.firebaseapp.com',
    storageBucket: 'evenlty-79b96.firebasestorage.app',
    measurementId: 'G-8LB21CK4SB',
  );
}
